### DISCUSSION TITLE
Oobabooga UI commands

### DISCUSSION THREAD

**Discussion by Vishal-Raghav** [oobabooga/text-generation-webui#3063] [Q&A]
How can I only show the text generation tab to the users. Is there any parameter in CLI to **restrict acces**s to other tabs in oobabooga?

python server.py --chat --multi-user --character Assistant --loader llama.cpp

**Comment by missionfloyd** [comment]
You can hide elements with CSS. To hide the tabs at the top, add this to [`main.css`](https://github.com/oobabooga/text-generation-webui/blob/main/css/main.css)
```css
.contain > div > .tabs > .tab-nav {
    display: none !important;
}
```
This isn't foolproof, however. Users can get around this if they know where to look.

**Reply by Vishal-Raghav** [reply]
Thanks mate it worked :). Is there any other css styles to hide the buttons and area below clear history in the main page?

**Reply by missionfloyd** [reply]
```css
#main > div > :nth-child(n+7), #extensions {
    display: none !important;
}
```
This should hide everything below the clear history button (it would be simpler if the elements had unique IDs).
