### DISCUSSION TITLE
Can someone create a 4 dummies WSL install?

### DISCUSSION THREAD

**Discussion by vdruts** [oobabooga/text-generation-webui#373] [General]
Tried installing, and then went onto the 4bit installation, only to receive one error after the next. No torch, no cuda.  I'm lost.

**Comment by ye7iaserag** [comment]
I have a docker image that I run over WSL, would that be beneficial for you?

**Comment by vdruts** [comment]
That would be great!

**Reply by ye7iaserag** [reply]
Here you go
First clone this repo
Then create a repositories folder and clone the `GPTQ-for-LLaMa` repo
Then get the `cuda-repo-debian11-11-7-local_11.7.1-515.65.01-1_amd64.deb` for cuda support and put it under `installers` folder
Dockerfile
```
FROM python:3.10.6-slim-bullseye

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y git build-essential software-properties-common gnupg

COPY . /app

WORKDIR /app

RUN dpkg -i /app/installers/cuda-repo-debian11-11-7-local_11.7.1-515.65.01-1_amd64.deb
RUN cp /var/cuda-repo-debian11-11-7-local/cuda-*-keyring.gpg /usr/share/keyrings/
RUN add-apt-repository contrib
RUN apt-get update
RUN apt-get -y install cuda \
 && apt -y remove nvidia-* \
 && rm -rf /var/cuda-repo-debian11-11-6-local

RUN --mount=type=cache,target=/root/.cache/pip pip install -r /app/requirements.txt
RUN --mount=type=cache,target=/root/.cache/pip pip install -r /app/extensions/google_translate/requirements.txt
RUN --mount=type=cache,target=/root/.cache/pip pip install -r /app/extensions/silero_tts/requirements.txt
#RUN --mount=type=cache,target=/root/.cache/pip python /app/repositories/GPTQ-for-LLaMa/setup_cuda.py install

# CMD python server.py --auto-devices --cai-chat --load-in-8bit --bf16 --listen --listen-port=8888 --model=pygmalion-6b

# CMD deepspeed --num_gpus=1 server.py --deepspeed --cai-chat --model pygmalion-6b

CMD docker/entrypoint.sh
```

docker-compose.yml
```
version: "3.3"  # optional since v1.27.0
services:
  text-generation-webui:
    build: .
    ports:
      - "8889:8888"
    stdin_open: true
    tty: true
    volumes:
      - .:/app
      - ./cache:/root/.cache
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
```

entrypoint.sh
```
#!/bin/bash

cd /app

set -euxo pipefail

set -x

# install LLAMA GPTQ
cd /app/repositories/GPTQ-for-LLaMa/ && python setup_cuda.py install > /dev/null 2>&1 && cd /app

# deepspeed --num_gpus=1 server.py --deepspeed --gpu-memory 10 --cai-chat --model=pygmalion-6b

# rwkv 14b 8bit with cpu offloading
# python server.py --cai-chat --listen --listen-port=8888 --model=RWKV-4-Pile-14B-20230228-ctx4096-test663.pth --rwkv-cuda-on --rwkv-strategy="cuda fp16i8 *25 -> cpu fp32"

# pygmalion-6b bf16
# python server.py --auto-devices --gpu-memory 10 --cai-chat --bf16 --listen --listen-port=8888 --model=pygmalion-6b

# pygmalion-6b 8bit
# python server.py --auto-devices --gpu-memory 10 --cai-chat --load-in-8bit --listen --listen-port=8888 --model=pygmalion-6b

# llama-13b-4bit
# python server.py --load-in-4bit --model llama-13b-hf --cai-chat --listen --listen-port=8888

# llama-30b-4bit
# python server.py --auto-devices --gpu-memory 10 --load-in-4bit --model llama-30b-hf --cai-chat --listen --listen-port=8888

# OPT-13B-Erebus
# python server.py --auto-devices --gpu-memory 10 --cai-chat --bf16 --listen --listen-port=8888 --model=OPT-13B-Erebus

# GPT-NeoXT-Chat-Base-20B 8bit
# python server.py --auto-devices --gpu-memory 8 --cai-chat --load-in-8bit --listen --listen-port 8888 --model=GPT-NeoXT-Chat-Base-20B
```
Uncomment the line for the model you want to load in the entry point file

Hope this helps
