### ISSUE TITLE
Improve Docker Instructions for Linux CPU users

### ISSUE THREAD

**Issue by gwpl** [oobabooga/text-generation-webui#2520]
I've followed current Docker instructions, as I am cpu users, I've done following:

As in current instructions https://github.com/oobabooga/text-generation-webui#alternative-docker 

```
ln -s docker/{Dockerfile,docker-compose.yml,.dockerignore} .
cp docker/.env.example .env
# Edit .env and set TORCH_CUDA_ARCH_LIST based on your GPU model
```

As I am  CPU user, in `.env` file, I commented out `TORCH_CUDA_ARCH_LIST` variable (and later script detected it and wrote "I assume blank"), and added `--cpu` to CLI_ARGS variable with parameters

```
docker compose up --build
```

Unfortunately ending up with:

```
#0 39.22   File "/build/venv/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1773, in _get_cuda_arch_flags
#0 39.22     arch_list[-1] += '+PTX'
#0 39.22 IndexError: list index out of range
------
failed to solve: process "/bin/sh -c . /build/venv/bin/activate &&     python3 setup_cuda.py bdist_wheel -d ." did not complete successfully: exit code: 1
```

more in https://gist.github.com/gwpl/20e05f58b64f18a395f82c386f15e529

versions:

```
$ docker compose version
Docker Compose version 2.18.1
```

**Comment by Reezlaw** [comment]
I don't think this is specific to CPU users, I just had the exact same problem building with CUDA and btw I used the normal procedure that used to work flawlessly. Something is broken in the requirements I think

**Comment by authcompanion** [comment]
As a CPU user - I'm here to report the same issue repo, and resulting error! Thank you for the enhancement consideration.

**Comment by pabl-o-ce** [comment]
[try this](https://www.reddit.com/r/LocalLLaMA/comments/13icz7y/minimal_docker_setup_for_cpu_based_oobabooga_text/)

**Comment by gwpl** [comment]
Thank you! It was overlook on my side! However still I encounter errors.
Let me update on current state of things:

* downloaded models using `python download-model.py` according to README.md 
*  wrapped it inside `download-example-models.sh` and now call automatically from `run.sh`

and getting new error:

```
$ ./run.sh
(...)
 => => naming to docker.io/library/text-generation                                                 0.0s
+ docker compose up
[+] Building 0.0s (0/0)                                                                                 
[+] Running 1/0
 ✔ Container text-generation-webui  Created                                                        0.0s 
Attaching to text-generation-webui
text-generation-webui  | /opt/conda/envs/textgen/lib/python3.10/site-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
text-generation-webui  |   warn("The installed version of bitsandbytes was compiled without GPU support. "
text-generation-webui  | INFO:Loading Wizard-Vicuna-13B-Uncensored.ggml.q5_1.bin...
text-generation-webui  | ERROR:The path to the model does not exist. Exiting.
^Ttext-generation-webui  | ERROR:No model is loaded! Select one in the Model tab.
text-generation-webui  | ERROR:No model is loaded! Select one in the Model tab.

```

* run.sh , download-example-models.sh and updated docker-compose.yml
* https://github.com/VariousForks/text-generation-webui/commits/i2520_reddit_13icz7y
    * https://github.com/VariousForks/text-generation-webui/commit/8cbf92632dba6fc40f10588d4c34d1cc39a05ac8

**Comment by pabl-o-ce** [comment]
Hello!

you don't have to use the download of `oobabooga` it wont work.

Have to download the `GGML` models manually following this steps:

1) create new dir for models like:
```sh
mkdir ggml-models
```
or erase everything in dir `models` to use the same one

2) Download the model you like in the models directory for example:
```sh
cd models // or cd ggml-models

curl -L -o  wizardlm-30b.ggmlv3.q6_K.bin https://huggingface.co/TheBloke/WizardLM-30B-GGML/resolve/main/wizardlm-30b.ggmlv3.q6_K.bin
```

3) Now set model file `docker-compose.yml` setting the model you download and the path your are using on the setup:

```yml
version: '3.8'
services:
  text-generation-webui:
    container_name: text-generation-webui
    restart: always
    volumes:
      - 'models:/models'
    ports:
      - '7860:7860'
      - '5005:5005'
      - '5000:5000'
    image: 'text-generation:latest'
    ulimits:
      memlock: -1
    mem_limit: 20gb
    command:
      [
        "--model",
        "wizardlm-30b.ggmlv3.q6_K.bin",
        "--extension",
        "api",
        "--api",
        "--cpu",
        "--mlock",
        "--listen",
        "--listen-port",
        "7860"
      ]
```
