### ISSUE TITLE
Ability to print chat

### ISSUE THREAD

**Issue by levicki** [oobabooga/text-generation-webui#2745]
**Description**

When you chat with the bot and send pictures, and use Stable Diffusion to generate images in responses you get a nicely ilustrated story. Sadly, if you try to invoke print dialog from the browser, it tries to print the whole UI with the chat part cut off.

It would be nice to have have a Print Chat button which would invoke browser print dialog just for the chat `div` with images stretched to full page width (A4 or Letter), and without surrounding UI. The idea is to actually be able to use Print to PDF to save the whole chat with photos into a PDF document.

I think this could be even hacked together with Tampermonkey script (I did similar thing for one website), but I am not so familiar with Gradio that much so it would take me more time to figure it out than if someone who knows it went in and added a print button.

**Comment by missionfloyd** [comment]
Something like this should work (`chat.css`). It's not quite there though,
```css
@media print {
    body {
        visibility: hidden;
    }

    .chat {
        visibility: visible;
        position: absolute;
        left: 0;
        top: 0;
        max-width: none;
        max-height: none;
        width: 100%
        height: fit-content;
    }
}
```
