### ISSUE TITLE
ModuleNotFoundError: No module named 'torch' when installer installs xformers

### ISSUE THREAD

**Issue by sammcj** [oobabooga/text-generation-webui#4255]
### Describe the bug

When building the current main branch, a fatal error is encountered when the install process attempts to install 'torch'.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

docker-compose with something like:

```yaml
services:
  textgen:
    build:
      context: https://github.com/oobabooga/text-generation-webui.git#main
      dockerfile: docker/Dockerfile
      args:
        - "TORCH_CUDA_ARCH_LIST=8.6;8.6+PTX"
        - GPUS=all
        - CMAKE_ARGS="-DLLAMA_BLAS=ON -DLLAMA_CUBLAS=on -DLLAMA_CLBLAST=on -DLLAMA_HIPBLAS=on -DLLAMA_F16C=on -DLLAMA_AVX512=on -DLLAMA_AVX2=on -DLLAMA_FMA=on"
        - FORCE_CMAKE=1
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: ["compute", "utility", "graphics"]
```

and run:

```shell
docker-compose build textgen
```

### Logs

```shell
28.57 Collecting xformers
28.57   Obtaining dependency information for xformers from https://files.pythonhosted.org/packages/c7/b4/9f8bea4204f8482c9c9c64bcf86bd209ccfb2ebdb27e3590ef4c1e87b743/xformers-0.0.21-cp310-cp310-manylinux2014_x86_64.whl.metadata
28.59   Downloading xformers-0.0.21-cp310-cp310-manylinux2014_x86_64.whl.metadata (1.0 kB)
28.59   Obtaining dependency information for xformers from https://files.pythonhosted.org/packages/4b/b0/dfbb3b0ceafdb73cd1b2bbe33f65dc1c5c47dcb0d4b03ba6f95da6557306/xformers-0.0.20-cp310-cp310-manylinux2014_x86_64.whl.metadata
28.61   Downloading xformers-0.0.20-cp310-cp310-manylinux2014_x86_64.whl.metadata (1.1 kB)
28.86 Collecting pyre-extensions==0.0.29 (from xformers)
28.88   Downloading pyre_extensions-0.0.29-py3-none-any.whl (12 kB)
28.90 Collecting xformers
29.15   Downloading xformers-0.0.19-cp310-cp310-manylinux2014_x86_64.whl (108.2 MB)
34.61      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 108.2/108.2 MB 8.7 MB/s eta 0:00:00
34.72   Downloading xformers-0.0.18-cp310-cp310-manylinux2014_x86_64.whl (123.8 MB)
42.10      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 123.8/123.8 MB 8.1 MB/s eta 0:00:00
42.19 Collecting pyre-extensions==0.0.23 (from xformers)
42.21   Downloading pyre_extensions-0.0.23-py3-none-any.whl (11 kB)
42.21 Collecting xformers
42.46   Downloading xformers-0.0.17-cp310-cp310-manylinux2014_x86_64.whl (123.6 MB)
47.23      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 123.6/123.6 MB 16.4 MB/s eta 0:00:00
47.34   Downloading xformers-0.0.16-cp310-cp310-manylinux2014_x86_64.whl (50.9 MB)
49.87      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.9/50.9 MB 34.3 MB/s eta 0:00:00
49.92   Downloading xformers-0.0.13.tar.gz (292 kB)
49.93      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 292.5/292.5 kB 40.5 MB/s eta 0:00:00
49.98   Preparing metadata (setup.py): started
50.07   Preparing metadata (setup.py): finished with status 'error'
50.07   error: subprocess-exited-with-error
50.07
50.07   × python setup.py egg_info did not run successfully.
50.07   │ exit code: 1
50.07   ╰─> [6 lines of output]
50.07       Traceback (most recent call last):
50.07         File "<string>", line 2, in <module>
50.07         File "<pip-setuptools-caller>", line 34, in <module>
50.07         File "/tmp/pip-install-9razuolw/xformers_f3af0394254345af8861d4b4ebaefcb5/setup.py", line 18, in <module>
50.07           import torch
50.07       ModuleNotFoundError: No module named 'torch'
50.07       [end of output]
50.07
50.07   note: This error originates from a subprocess, and is likely not a problem with pip.
50.07 error: metadata-generation-failed
50.07
50.07 × Encountered error while generating package metadata.
50.07 ╰─> See above for output.
50.07
50.07 note: This is an issue with the package mentioned above, not pip.
50.07 hint: See above for details.
------
failed to solve: process "/bin/sh -c . /app/venv/bin/activate &&     pip3 install --upgrade pip setuptools wheel &&     pip3 install torch torchvision torchaudio sentence_transformers xformers" did not complete successfully: exit code: 1
```

### System Info

```shell
- Docker: version 24.0.6, build ed223bc
- Branch: main (2023-10-11)
- CUDA: yes, with RTX3090 and the nvidia runtime
```
