### ISSUE TITLE
Settings for which tabs should be visible

### ISSUE THREAD

**Issue by PyroGenesis** [oobabooga/text-generation-webui#4748]
**Description**

I want to be able to control which tabs are visible in the Web UI, either through `settings.yaml` or command-line arguments. This is so that I can have someone else use the Web UI without them having access to tabs like Training, Session, etc.

If there is a way to do this currently, please let me know.

**Comment by PyroGenesis** [comment]
To do this myself, I added the following CSS to `css/main.css` as a workaround:
```css
#default-tab-button,
#notebook-tab-button,
#parameters-button,
#model-tab-button,
#training-tab-button,
#session-tab-button {
    display: none;
}
```
