### ISSUE TITLE
Config not loading the instruction template

### ISSUE THREAD

**Issue by nephi-dev** [oobabooga/text-generation-webui#4939]
### Describe the bug

I have a config with a instruction template to load with the models, this worked before, but now is not working
```yaml
  ...
  mode: chat-instruct
  chat_style: cai-chat
  preset: Midnight Enigma
  instruction_template: ChatML
```

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Create a config with a given instruction template and expect it to load, but when it loads it's on a default(custom) template.

### Screenshot

![image](https://github.com/oobabooga/text-generation-webui/assets/48372168/05fdcdcd-934c-47f6-8d56-004148c492e1)

### Logs

```shell
No errors, just wrong functionality.
```

### System Info

```shell
win 11
nvidia rtx 4060 ti 16gb
```
