### ISSUE TITLE
Docker version doesn't retain chat history

### ISSUE THREAD

**Issue by Reezlaw** [oobabooga/text-generation-webui#5040]
### Describe the bug

The chat history seems to be saved inside the container and not in a mounted volume, making it as ephemeral as the container itself.
I believe past chats should be saved in a permanent file within the text-generation-webui folder so they're persistent even when the container is rebuilt.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

*Save/rename a few chats *
docker compose down
git pull
docker compose up --build
*chats are gone *

### Logs

```shell
N/A
```

### System Info

```shell
Manjaro Linux
Nvidia RTX 3090
docker 24.0.7
docker compose 2.23.3
```

**Comment by Luxocracy** [comment]
I was having the same issue, here's what I did to keep the logs and settings persistent on my machine.

- Copy the settings-template.yaml to settings.yaml `cp settings-template.yaml settings.yaml`
- Create a "logs" folder with the appropriate permissions `mkdir logs && chmod 777 logs` (I was having issues with the logs folder not being writable by the app, so I just gave it full permissions)
- Create a docker-compose.override.yml
- Add the following content to it:

```
version: "3.3"
services:
  text-generation-webui:
    volumes:
      - ./settings.yaml:/home/app/text-generation-webui/settings.yaml
      - ./logs:/home/app/text-generation-webui/logs
```

This allows the settings and logs to be persistent on the host machine.
