### ISSUE TITLE
Scrolling for sidebars

### ISSUE THREAD

**Issue by Alkohole** [oobabooga/text-generation-webui#6407]
**Description**
I propose to add scrolling for sidebars, so that these panels do not fly out of the window when the window shrinks.

**Additional Context**

The [part](https://github.com/oobabooga/text-generation-webui/blob/f98431c7448381bfa4e859ace70e0379f6431018/css/main.css#L726C1-L744C2) that needs to be changed: 
```css
@media screen and (width >= 1327px) {
    #past-chats-row {
        position: absolute;
        top: 36px;
        left: 0;
        width: calc(0.5*(var(--document-width) - 880px - 120px - 16px*2));
        max-width: 300px;
        margin-left: calc(-0.5*(var(--document-width) - 880px - 14px - 16px * 2));
    }

    #chat-controls {
        position: absolute;
        top: 16px;
        right: 0;
        width: calc(0.5*(var(--document-width) - 880px - 120px - 16px*2));
        max-width: 400px;
        margin-right: calc(-0.5*(var(--document-width) - 880px - 14px - 16px * 2));
    }
}
```

Simply adding a height and overflow-y parameter does the scrolling function quite well:
```css
overflow-y: auto;
height: 85lvh; /* or calc(100% - 35px) for a more precise fit */
```

**Examples**
- Original:
![original](https://github.com/user-attachments/assets/ac0a06b7-6841-4c3a-abb6-177e43416845)

- With scroll:
![with_scroll](https://github.com/user-attachments/assets/6878a5d7-0758-460a-9082-6009109350e3)
