### ISSUE TITLE
Unable to load DeepSeek-R1-UD-Q2_K_XL but works with llama.cpp

### ISSUE THREAD

**Issue by ElliottLester** [oobabooga/text-generation-webui#6715]
### Describe the bug

Unable to load DeepSeek-R1-UD-Q2_K_XL.gguf

This is possible using llama.cpp directly logs attached.

at commit 9ac4d81c8bc8fd1d72817949be27e2b6cd7c7c40 (HEAD -> main, tag: v2.4, origin/main, origin/HEAD)

settings for webui
```
DeepSeek-R1-UD-Q2_K_XL$:
  loader: llama.cpp
  n_gpu_layers: 16
  threads: 30
  threads_batch: 0
  n_batch: 2048
  n_ctx: 8192
  cache_type: q4_0
  tensor_split: ''
  rope_freq_base: 10000
  compress_pos_emb: 0.05
  attention_sink_size: 0
  tensorcores: false
  flash_attn: false
  streaming_llm: false
  cpu: false
  row_split: false
  no_offload_kqv: false
  no_mul_mat_q: false
  no_mmap: false
  mlock: false
  numa: false
```
[text-generation-webui.log](https://github.com/user-attachments/files/18596122/text-generation-webui.txt)

command line for llama-server
```
GGML_CUDA_ENABLE_UNIFIED_MEMORY=1

~/llama.cpp/llama-server \
    --model ./models/DeepSeek-R1-UD-Q2_K_XL/DeepSeek-R1-UD-Q2_K_XL.gguf \
    --cache-type-k q4_0 \
    --threads 30 --prio 1 \
    --n-gpu-layers 16 \
    --temp 0.7 \
    --ctx-size 8192 \
    --host 0.0.0.0
```
[llama.cpp.log](https://github.com/user-attachments/files/18596123/llama.cpp.txt)

### Is there an existing issue for this?

- [x] I have searched the existing issues
- might be related to [6679](https://github.com/oobabooga/text-generation-webui/issues/6679)
- not resolved by commit 9ac4d81c8bc8fd1d72817949be27e2b6cd7c7c40

### Reproduction

download [DeepSeek-R1-GGUF](https://huggingface.co/unsloth/DeepSeek-R1-GGUF)

attempt to load with above settings, and fails on text UI.

### Logs

```shell
see linked files in description or:
[text-generation-webui.log](https://github.com/user-attachments/files/18596122/text-generation-webui.txt)
[llama.cpp.log](https://github.com/user-attachments/files/18596123/llama.cpp.txt)
```

### System Info

```shell
[NVIDIA RTX A6000], [NVIDIA RTX A5500] , AMD Ryzen Threadripper PRO 7975WX 32-Cores, 512GB ram
```

**Comment by oobabooga** [comment]
> llama_init_from_model: V cache quantization requires flash_attn

you need to enable flash-attention

**Comment by ElliottLester** [comment]
that stills fails the only change in the logs is
```
llama_init_from_model: flash_attn requires n_embd_head_k == n_embd_head_v - forcing off
```

**Comment by henryclw** [comment]
> > llama_init_from_model: V cache quantization requires flash_attn
> 
> you need to enable flash-attention

I get this error with `--flash-attn` enabled.

**Comment by divine-taco** [comment]
flash attention is likely getting forced off by llamacpp
```
llama_init_from_model: flash_attn requires n_embd_head_k == n_embd_head_v - forcing off
```
-ctk and -ctv need to be the same.

**Comment by ElliottLester** [comment]
The issue is that we can't quantize layers on the cpu below f16 so this works:
```
DeepSeek-R1-UD-Q2_K_XL$:
  loader: llama.cpp
  n_gpu_layers: 16
  threads: 30
  threads_batch: 0
  n_batch: 2048
  n_ctx: 4096
  cache_type: fp16
  tensor_split: ''
  rope_freq_base: 10000
  compress_pos_emb: 0.05
  attention_sink_size: 0
  tensorcores: false
  flash_attn: true
  streaming_llm: false
  cpu: false
  row_split: false
  no_offload_kqv: false
  no_mul_mat_q: false
  no_mmap: false
  mlock: false
  numa: false
```
