### ISSUE TITLE
Support for Raven RWKV input + instructions interface

### ISSUE THREAD

**Issue by elsatch** [oobabooga/text-generation-webui#714]
Hello,

I am writing to request the addition of a new feature for the CAI chat interface, specifically, the ability to differentiate between instruction and input. I came across an implementation in the Raven-RWKV-7B model at https://huggingface.co/spaces/BlinkDL/Raven-RWKV-7B and believe that adopting this feature can greatly enhance the user experience and organization for other models as well.

Currently, users need to include both instruction and input within the same text, which can sometimes be confusing for the model. With this proposed feature, users would be able to separate the instruction from the input, allowing for clearer communication with the AI model.

Here are some examples taken from the Raven site:

Example 1:

    Instruction: Write a story using the following information
    Input: A man named Alex chops a tree down

Example 2:

    Instruction: What is the color of these things?
    Input: sun, moon, apple

By differentiating between instruction and input, it could be possible to achieve better organization and potentially improve the model's understanding and response quality. I kindly ask for your support in implementing this feature and would be glad to contribute if needed.

Thank you for considering this request, and I am looking forward to your thoughts on this matter.

Best regards,
César

**Comment by oobabooga** [comment]
Would the inclusion of prompt templates solve this? For instance, Open Assistant requires prompts in the format

```
<|prompter|>Write a story about future of AI development<|endoftext|><|assistant|>
```

We could have a "prompt template" like

```
<|prompter|>%input%<|endoftext|><|assistant|>
```

The input in the text box would then simply be "Write a story about future of AI development", which would be replaced with the full formatted prompt before the text generation begins.

**Comment by tensiondriven** [comment]
I think longer-term, this "template" is going to want to be a gradio-based template.  Chat and Prompt Completion are already examples of this, but are currently hard-coded.  [ReAct](https://arxiv.org/abs/2210.03629) and Raven will introduce the need for formatting inputs and transforming them before passing them off to the model, so I I think @elsatch is onto something!

For OpenAssistant, and other projects that collect responses, I could also see these extensions allowing users to opt-in to providing their chats as training data, which would allow them to use text-generation-webui instead of rolling their own, which i think is what such projects do now.  So that's kind of a different dimension of the problem but i think it would also be served by expanding the extension API.

For something like this, I could see these being 10-line extensions that expose a function that returns Gradio blocks to provide their templating, do a little transformation, and return a string to the model (or modify `shared`)

This might be a minor detail or unintentional, but wanted to mention:
> CAI chat interface
I don't see this as a chat-specific feature, and particularly not a Chracter-AI-related chat feature, since CAI is an "emulation mode" for a  different service.  Seems like it would be more appropriate to use in a prompt completion format.

**Comment by elsatch** [comment]
Thanks for your responses and suggestions. I assume in the future we will have a broader variety of prompt formats/templates, based on the training datasets used for each model.

I wonder if this could be solved inheriting some of the features of Automatic1111. AFAIK, some of the models require custom VAE to work. To simplify the load of those files, you need a custom configuration file (yaml format) that has the same name as the model file. If no file is present, load the defaults. If file exists, customize the model/UI load based on the custom parameters.

So in this particular case, you could download:
- RWKV-4-Raven-7B-v6-Eng-20230331-ctx4096.pth 
- RWKV-4-Raven-7B-v6-Eng-20230331-ctx4096.yaml file. 
 
Inside the config file, you could find information about the format like this:

```yaml
webui_config:
  title: "RWKV-4-Raven-7B-v6-Eng-20230401-ctx4096"
  prompt_generation:
    function: "generate_prompt"
    parameters:
      - name: "instruction"
        type: "string"
        required: true
      - name: "input"
        type: "string"
        required: false
    returns:
      - name: "ctx"
        type: "string"
        template: "generate_prompt(%instruction%, %input%)"
```

Note: This particular information was taken from the actual [Raven-RWKV-7B app.py](https://huggingface.co/spaces/BlinkDL/Raven-RWKV-7B/blob/main/app.py) and converted to a yaml using GPT-4 and customized later.

For the OpenAssistant Model, it could be something like this:

```yaml
webui_config:
  title: "OpenAssistant-7B-ctx4096"
  prompt_generation:
    function: "generate_prompt"
    parameters:
      - name: "input"
        type: "string"
        required: true
    returns:
      - name: "output"
        type: "string"
        template: "<|prompter|>%input%<|endoftext|><|assistant|>"
```

I am just getting started with Gradio/LLMs, so this might be overkill or something supported in some other simpler format.
