### ISSUE TITLE
Can we have a docker installation option?

### ISSUE THREAD

**Issue by ye7iaserag** [oobabooga/text-generation-webui#87]
This is just a suggestion, having docker container support would make things way easier to install and isolate, also with docker compose you can start everything including gpu support with a simple `docker-compose up`

**Comment by oobabooga** [comment]
`conda` is contained, and so is `micromamba` (for the 1-click installers). 

What niche would docker serve?

**Comment by ye7iaserag** [comment]
A one command to run on all platforms and a guarantee that it works

Btw I've already created the `Dockerfile` if anyone needs it

```
FROM python:3.10.6-slim-bullseye

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y git software-properties-common gnupg

COPY . /app

WORKDIR /app

RUN dpkg -i /app/installers/cuda-repo-debian11-11-7-local_11.7.1-515.65.01-1_amd64.deb
RUN cp /var/cuda-repo-debian11-11-7-local/cuda-*-keyring.gpg /usr/share/keyrings/
RUN add-apt-repository contrib
RUN apt-get update
RUN apt-get -y install cuda \
 && apt -y remove nvidia-* \
 && rm -rf /var/cuda-repo-debian11-11-6-local

RUN --mount=type=cache,target=/root/.cache/pip pip install -r /app/requirements.txt
RUN --mount=type=cache,target=/root/.cache/pip pip install -r /app/extensions/google_translate/requirements.txt
RUN --mount=type=cache,target=/root/.cache/pip pip install -r /app/extensions/silero_tts/requirements.txt

CMD python server.py --auto-devices --cai-chat --load-in-8bit --bf16 --listen --listen-port=8888
```

I also created the following `docker-compose.yml`
```
version: "3.3"  # optional since v1.27.0
services:
  text-generation-webui:
    build: .
    ports:
      - "8889:8888"
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
```

and had to add those dependencies to the bottom of the `requirements.txt`
```
--extra-index-url https://download.pytorch.org/whl/cu117
torchaudio
torch==1.13.1+cu117
torchvision==0.14.1+cu117
```

feel free to close the PR, and for anyone coming from search, you're welcome :D
